<a href="https://colab.research.google.com/github/sharvilpawar123-source/numpy-operations/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

#Basic Array Creation

In [2]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
l=[[1,2,3],[4,5,6]]
np.array(l)

array([[1, 2, 3],
       [4, 5, 6]])

#Array Generation Function

In [5]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros([6,6])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
arr=np.linspace(1,10,3) # equally divide in 3 parts from 1 to 10
arr

array([ 1. ,  5.5, 10. ])

#Random Generation Function


In [11]:
np.random.rand(5) #random val from 0 to 1

array([0.34967323, 0.46785248, 0.24331545, 0.6970806 , 0.86101827])

In [12]:
np.random.randn(5) #random val from -3 to 3

array([ 0.68819327, -0.2663296 ,  0.1586934 ,  1.39804637, -1.28719154])

In [14]:
np.random.randint(1,10,5) # from 1 to 10 take any 5 vals

array([5, 2, 1, 1, 7])

#Array Attributes

In [20]:
arr=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr.shape # arr.shape tells the shape

(3, 3)

In [24]:
arr.size

9

In [25]:
arr.dtype

dtype('int64')

#Arr methods

In [26]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr.min()

np.int64(1)

In [29]:
arr.max()

np.int64(9)

In [31]:
arr.argmax() #idx of max Val

np.int64(8)

In [32]:
arr.argmin() #idx of min Val

np.int64(0)

In [33]:
arr.sum()

np.int64(45)

In [34]:
arr.sum(axis=0) #col wise sum

array([12, 15, 18])

In [35]:
arr.sum(axis=1) #row wise"

array([ 6, 15, 24])

In [36]:
arr.mean() #mean

np.float64(5.0)

In [37]:
arr.std() #standard Deviation

np.float64(2.581988897471611)

#Reshape and Resize

In [38]:
np.arange(1,31).reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

#Arr Indexing and slicing

In [39]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr[0]

array([1, 2, 3])

In [41]:
arr[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [42]:
arr[0,0]

np.int64(1)

#Boolean Indexing

In [44]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [48]:
# to get only even val
bool_index=arr%2==0
bool_index


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [49]:
arr=arr[bool_index]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

#Arr arithmatic operation

In [50]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr1+arr2

array([ 6,  8, 10, 12])

In [51]:
arr1-arr2

array([-4, -4, -4, -4])

In [52]:
arr1*arr2

array([ 5, 12, 21, 32])

#Broad Casting


In [54]:
arr=np.array([1,2,3,4])
arr+2 #broad Casting

array([3, 4, 5, 6])

#Deep Copy and Shallow Copy

In [55]:
arr

array([1, 2, 3, 4])

In [60]:
arr3=arr
arr3

array([1, 2, 3, 4])

In [61]:
arr3[0]=99
arr3

array([99,  2,  3,  4])

In [62]:
arr #changed in arr also

array([99,  2,  3,  4])

In [66]:
#just apply changes on copy
arr3=arr.copy()
arr3[0]=1

arr3


array([1, 2, 3, 4])

In [68]:
arr #arr not changed as we change arr3

array([99,  2,  3,  4])

#Matrix Operation

In [70]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a@b #multiplication

array([[19, 22],
       [43, 50]])

In [71]:
np.dot(a,b) # dot product

array([[19, 22],
       [43, 50]])

In [73]:
np.matmul(a,b) #multiplication

array([[19, 22],
       [43, 50]])

In [74]:
a.T #transpose

array([[1, 3],
       [2, 4]])

#Advance Arr manipulation

In [75]:
a

array([[1, 2],
       [3, 4]])

In [76]:
b

array([[5, 6],
       [7, 8]])

In [78]:
np.vstack((a,b)) #vertical stack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [80]:
np.hstack((a,b)) #horizontal stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

#Spliting Arr

In [81]:
np.hsplit(a,2) #horizontal split

[array([[1],
        [3]]),
 array([[2],
        [4]])]

In [82]:
np.vsplit(a,2) #vertical split

[array([[1, 2]]), array([[3, 4]])]